export const STRIPE_CONFIG = {
    MAXIMUM_CREDITS:20000,
    MINIMUM_CREDITS:50,
    CREDITS_STEP:10,
}

export const CREDITS_REQUIREMENT = {
    UPLOAD_PDF_PER_TEN_PAGE: 30,
    GENERATE_MCQ: 10,
    ANSWER_QUESTION_FROM_PDF: 5,
    ANSWER_GENERAL_QUESTION: 1,
};
  